version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-1-{{ checksum "package-lock.json" }}
            - dependency-cache-1-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-1-{{ checksum "package-lock.json" }}

      - run: npm run ci:build
      - persist_to_workspace:
          root: "."
          paths:
            - node_modules
            - package-lock.json

  verify_formatting:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: "."

      - restore_cache:
          key: dependency-cache-1-{{ checksum "package-lock.json" }}

      - run: npm run prettier

workflows:
  version: 2
  build_and_verify:
    jobs:
      - build
      - verify_formatting:
          requires:
            - build
