export default {
    gravity: 400,
    jumpForce: 700,
    platformSpeed: 4,
    platformSpeedIncrement: 0,
    windowHeight: 600,
    windowWidth: 800,
    purpleBox: 0x6400e4,
    purpleText: "#6400e4",
    whiteText: "#fff",
    blackText: "#000",
    backgroundColor: 0xf9f9f9,
    smallFontSize: "17px",
    mediumFontSize: "24px",
    largeFontSize: "48px",
    fontFamily: "sans-serif",
};
