export default {
    backgroundColor: 0xffffff,
    blackText: "#000",
    extraLargeFontSize: "48px",
    fontFamily: "Apercu, sans-serif",
    gravity: 400,
    jumpForce: 700,
    largeFontSize: "32px",
    mediumFontSize: "24px",
    parent: null,
    platformSpeed: 4,
    platformSpeedIncrement: 0,
    purpleBox: 0x6400e4,
    purpleText: "#6400e4",
    smallFontSize: "16px",
    whiteText: "#fff",
    windowHeight: 600,
    windowWidth: 800,
};
